"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { useSystemLens } from "@/features/system-lens/system-lens-store";
import { ConsultationForm } from "./consultation-form.client";
import { evaluateIncidentReview, type ReviewAnswers } from "./evaluate-review";
import { demoLawPhoneHref } from "./data";

type Question={key:string;legend:string;mode:"radio"|"checkbox";optional?:boolean;options:[string,string][]};
type Step={title:string;short:string;intro:string;why:string;questions:Question[]};
const steps:Step[]=[
  {title:"Immediate safety and medical needs",short:"Safety & care",intro:"Before any legal question, make sure the next action does not overlook immediate health or safety needs.",why:"We ask only to surface a human safety path. This interface cannot assess medical urgency.",questions:[{key:"safety",legend:"Which statement best fits right now?",mode:"radio",options:[["danger","Someone may be in immediate danger"],["urgent-care","There are severe, new, or worsening symptoms that may need prompt care"],["stable","There is no immediate danger I know of"],["not-sure","I am not sure"]]}]},
  {title:"Incident context",short:"Incident context",intro:"Broad location, type, and timing help identify what records and professional questions may matter.",why:"Jurisdiction and timing can affect legal rights. This demonstration never calculates a deadline.",questions:[{key:"jurisdiction",legend:"Where did the incident occur?",mode:"radio",options:[["california","California"],["other-us","Another U.S. state"],["outside-us","Outside the United States"],["not-sure","I am not sure"]]},{key:"incident-type",legend:"What kind of incident was it?",mode:"radio",options:[["vehicle","Vehicle collision"],["pedestrian","Pedestrian incident"],["cyclist","Cyclist or mobility-device incident"],["property","Unsafe property condition or fall"],["other","Another kind of incident"],["not-sure","I am not sure"]]},{key:"incident-age",legend:"About how long ago?",mode:"radio",options:[["days-weeks","Days or weeks"],["months","Several months"],["year-plus","A year or more"],["not-sure","I am not sure"]]}]},
  {title:"People and insurance involvement",short:"Parties & coverage",intro:"Identify the kinds of people, organizations, or coverage that may be involved—without naming anyone here.",why:"Multiple parties or policies can change what information a lawyer may need to review.",questions:[{key:"parties",legend:"Who or what may be involved? Select all that fit.",mode:"checkbox",options:[["individual","Another individual"],["business","A business or employer"],["government","A public entity or roadway"],["rideshare","A rideshare or delivery platform"],["unknown","I am not sure"]]},{key:"coverage",legend:"What coverage is known?",mode:"checkbox",options:[["my-insurer","My insurer"],["other-insurer","Another party’s insurer"],["health","Health coverage"],["work","Work-related coverage"],["unknown","I am not sure"]]}]},
  {title:"Medical care received",short:"Medical care",intro:"Care history and instructions can help organize the next conversation. This is not a medical assessment.",why:"Records of care can show chronology and help identify missing documents. No answer changes your right to request human help.",questions:[{key:"care",legend:"What care has occurred? Select all that fit.",mode:"checkbox",options:[["emergency","Emergency or urgent care"],["doctor","Primary doctor or clinic"],["specialist","Specialist"],["therapy","Physical, occupational, or other therapy"],["other-care","Another kind of care"],["none","No care yet"],["prefer-not","Prefer not to answer"]]}]},
  {title:"Physical pain and symptom changes",short:"Physical impact",intro:"Use broad descriptions only. Do not enter diagnoses, records, or detailed medical information.",why:"A dated record of changes can be useful to care providers and counsel, but this interface does not diagnose or judge credibility.",questions:[{key:"pain",legend:"What has changed since the incident? Select all that fit.",mode:"checkbox",options:[["worsening","Symptoms are worsening"],["new-symptoms","New symptoms appeared"],["stable","Symptoms are present but stable"],["improving","Symptoms are improving"],["none","No physical symptoms"],["not-sure","I am not sure"],["prefer-not","Prefer not to answer"]]}]},
  {title:"Daily life and mobility",short:"Daily limitations",intro:"Think about observable changes in normal tasks rather than trying to describe them in legal terms.",why:"Daily function can be easier to understand through concrete changes in activity, support, and mobility.",questions:[{key:"daily",legend:"Which areas changed? Select all that fit.",mode:"checkbox",options:[["mobility","Walking, stairs, movement, or transportation"],["self-care","Personal care"],["household","Household tasks"],["caregiving","Caregiving or family responsibilities"],["driving","Driving or traveling"],["sleep-limit","Sleep because of physical symptoms"],["none","No daily limitation"],["prefer-not","Prefer not to answer"]]}]},
  {title:"Work and financial disruption",short:"Work & finances",intro:"Use broad categories. Do not enter employer names, income amounts, account details, or documents.",why:"Work changes and practical expenses can create records that are useful to preserve.",questions:[{key:"work",legend:"What changed? Select all that fit.",mode:"checkbox",options:[["missed","Missed work"],["reduced","Reduced hours or duties"],["job-change","Job status or role changed"],["expenses","New incident-related expenses"],["household-help","Paid or unpaid household help"],["none","No work or financial change"],["not-applicable","Not applicable"],["prefer-not","Prefer not to answer"]]}]},
  {title:"Optional emotional and psychological effects",short:"Emotional effects",intro:"This topic is optional. You may skip it or choose “Prefer not to answer” with no effect on access to the result or human help.",why:"Sleep, concentration, anxiety, or avoidance can affect daily life. This is not a diagnosis and does not create a case score.",questions:[{key:"psych",legend:"Have you noticed any of these changes? Select any, skip, or prefer not to answer.",mode:"checkbox",optional:true,options:[["anxiety","Anxiety or heightened worry"],["sleep","Sleep changes not already described"],["avoidance","Driving or travel avoidance"],["concentration","Concentration changes"],["distress","Emotional distress"],["none","No change noticed"],["prefer-not","Prefer not to answer"]]}]},
  {title:"Evidence and documentation",short:"Evidence",intro:"Identify what exists without uploading it. This demonstration does not accept files or photographs.",why:"Some evidence changes or is overwritten. A simple preservation plan can make the next conversation more useful.",questions:[{key:"evidence",legend:"What do you currently have or know about? Select all that fit.",mode:"checkbox",options:[["photos","Original photos or video"],["report","Incident or police report information"],["witness","Witness information"],["medical","Care or medical records"],["work","Work or expense records"],["camera-risk","A possible camera or digital record that may be overwritten"],["physical-item","A physical item that may matter"],["none","None of these yet"],["not-sure","I am not sure"]]}]},
  {title:"Insurance communication",short:"Insurance",intro:"Use broad categories only. Do not enter claim numbers, adjuster names, policy details, or message text.",why:"Recorded statements, releases, authorizations, offers, and mentioned deadlines may deserve prompt jurisdiction-specific review.",questions:[{key:"insurance",legend:"What has happened so far? Select all that fit.",mode:"checkbox",options:[["contact-only","Basic contact or claim setup"],["statement","A recorded or detailed statement was requested"],["release","A release or broad authorization was provided"],["offer","An offer was made"],["deadline-mentioned","Someone mentioned a deadline or scheduled proceeding"],["none","No insurer communication"],["not-sure","I am not sure"]]}]},
];

function selected(answers:ReviewAnswers,key:string,value:string){return answers[key]?.includes(value)??false;}
export function IncidentReview(){
  const router=useRouter();const [step,setStep]=useState(0);const [answers,setAnswers]=useState<ReviewAnswers>({});const [error,setError]=useState("");const [result,setResult]=useState(false);const titleRef=useRef<HTMLHeadingElement>(null);const record=useSystemLens(s=>s.record);
  const current=steps[step]!;const urgent=selected(answers,"safety","danger")||selected(answers,"safety","urgent-care");
  useEffect(()=>{titleRef.current?.focus();},[step,result]);
  const change=(question:Question,value:string,checked:boolean)=>setAnswers(existing=>{const before=existing[question.key]??[];return{...existing,[question.key]:question.mode==="radio"?[value]:checked?[...before.filter(item=>item!==value),value]:before.filter(item=>item!==value)}});
  const valid=()=>current.questions.every(question=>question.optional||(answers[question.key]?.length??0)>0);
  const next=()=>{if(!valid()){setError("Choose an answer for each required question before continuing.");return;}setError("");if(step<steps.length-1)setStep(step+1);else{setResult(true);const guidance=evaluateIncidentReview(answers);record({scope:"injury-law",type:"case_review_completed",signal:"The guided review was completed",response:"A non-scoring action plan was prepared",value:"Value delivered before lead capture",status:"derived"});record({scope:"injury-law",type:"evidence_plan_created",signal:"Evidence categories were reviewed",response:"Preservation actions and broad documentation gaps were organized",value:"A more prepared human conversation",status:"derived"});if(guidance.documentationGaps.length)record({scope:"injury-law",type:"documentation_gaps_identified",signal:"Documentation gaps were identified",response:"General missing-record categories surfaced without private details",value:"A clearer follow-up plan",status:"derived"});record({scope:"injury-law",type:"attorney_review_prompted",signal:"Human review remained available",response:"Jurisdiction-specific review was recommended without an eligibility conclusion",value:"A safe escalation path",status:"demo-preview"});}};
  const clear=()=>{setAnswers({});setStep(0);setResult(false);setError("");router.push("/showroom/injury-law");};
  if(result){const guidance=evaluateIncidentReview(answers);const download=()=>{const text=["Morrow & Vale demonstration — General action plan","",...guidance.safetyActions,"",`Human review: ${guidance.reviewTiming}`,"","Evidence preservation",...guidance.evidenceActions.map(x=>`- ${x}`),"","Documentation gaps",...(guidance.documentationGaps.length?guidance.documentationGaps:["No broad gap was identified from the selected categories."]).map(x=>`- ${x}`),"","General next steps",...guidance.generalNextSteps.map(x=>`- ${x}`),"","Limits",...guidance.assumptions.map(x=>`- ${x}`)].join("\n");const url=URL.createObjectURL(new Blob([text],{type:"text/plain"}));const a=document.createElement("a");a.href=url;a.download="general-next-step-plan.txt";a.click();URL.revokeObjectURL(url);};return <div className="il-review__body"><section className="il-review__panel il-result"><p className="il-review__step-label">Your general orientation</p><h1 ref={titleRef} tabIndex={-1}>A clear next-step record.</h1><p className="il-review__intro">This is useful general guidance—not a case score, legal conclusion, medical assessment, deadline calculation, or promise of representation.</p><div className="il-result__banner"><strong>Human review timing</strong><p>{guidance.reviewTiming}</p></div><ResultSection title="Safety and medical needs" items={guidance.safetyActions}/><ResultSection title="Evidence to preserve" items={guidance.evidenceActions}/><ResultSection title="Documentation gaps" items={guidance.documentationGaps.length?guidance.documentationGaps:["No broad gap was identified from the selected categories. A human review may still identify records that matter."]}/><ResultSection title="General next steps" items={guidance.generalNextSteps}/><div className="il-result__limits"><strong>Assumptions and limits</strong>{guidance.assumptions.map(item=><p key={item}>{item}</p>)}</div><div className="il-review__actions"><button className="il-button il-button--line" type="button" onClick={()=>{setResult(false);setStep(steps.length-1)}}>Back and edit</button><div><button className="il-button il-button--line" type="button" onClick={download}>Download general plan</button><button className="il-button il-button--ink" type="button" onClick={()=>window.print()}>Print</button></div></div><section className="il-result__contact"><p className="il-eyebrow" style={{color:"#d5a9b1"}}>Optional contact · After value</p><h2>Would a human conversation help?</h2><p>Only the contact fields below are processed for the no-send preview. None of your review answers are attached, transmitted, stored, or shown in the System Lens.</p><ConsultationForm source="case-review-result" compact/></section></section><ReviewRail step={10}/></div>}
  return <div className="il-review__body"><section className="il-review__panel"><p className="il-review__step-label">{current.short} · {step+1} of {steps.length}</p><h1 ref={titleRef} tabIndex={-1}>{current.title}</h1><p className="il-review__intro">{current.intro}</p><p className="il-review__why"><strong>Why we ask: </strong>{current.why}</p>{urgent&&<div className="il-result__banner" role="alert"><strong>Safety and care come first.</strong><p>Call 911 for immediate danger. Seek appropriate medical evaluation for severe, new, or worsening symptoms. You can also <a href={demoLawPhoneHref} style={{borderBottom:"1px solid"}}>use the human-help path</a> without finishing this review.</p></div>}{error&&<div className="il-review__error" role="alert" tabIndex={-1}>{error}</div>}{current.questions.map(question=><fieldset key={question.key} style={{marginBottom:"2rem"}}><legend>{question.legend}</legend><div className="il-choice-list">{question.options.map(([value,label])=><label className="il-choice" key={value}><input type={question.mode} name={question.key} value={value} checked={selected(answers,question.key,value)} onChange={event=>change(question,value,event.currentTarget.checked)}/><span>{label}</span></label>)}</div></fieldset>)}{step===1&&<div className="il-review__date"><label htmlFor="incident-date">Exact incident date <span>Optional</span></label><input id="incident-date" type="date" max={new Date().toISOString().slice(0,10)} value={answers["incident-date"]?.[0]??""} onChange={event=>setAnswers(existing=>({...existing,"incident-date":event.currentTarget.value?[event.currentTarget.value]:[]}))}/><small>This stays in volatile page memory and clears on refresh or exit. It is not evaluated, sent, saved, logged, or used to decide eligibility.</small></div>}<div className="il-review__actions"><button className="il-button il-button--line" type="button" onClick={clear}>Exit &amp; clear</button><div>{step>0&&<button className="il-button il-button--line" type="button" onClick={()=>{setError("");setStep(step-1)}}>Back</button>}<button className="il-button il-button--ink" type="button" onClick={next}>{step===steps.length-1?"Prepare my guidance":"Continue"}</button></div></div></section><ReviewRail step={step}/></div>;
}
function ReviewRail({step}:{step:number}){return <aside className="il-review__rail"><h2>Your review outline</h2><p>Step {Math.min(step+1,10)} of 10</p><ol>{steps.map((item,index)=><li key={item.short} aria-current={index===step?"step":undefined} data-complete={index<step}>{item.short}</li>)}</ol></aside>}
function ResultSection({title,items}:{title:string;items:string[]}){return <section className="il-result__section"><h2>{title}</h2><ul>{items.map(item=><li key={item}>{item}</li>)}</ul></section>}
