import { lawPhoneDisplay, lawPhoneHref } from "@/features/demos/injury-law/data";
export const metadata = { title: "Privacy Policy" };
export default function Page() { return <main id="injury-main" className="il-legal"><p className="il-eyebrow">Privacy</p><h1>Privacy Policy</h1><p><strong>Effective August 25, 2026.</strong> This policy explains how Lev &amp; On Law Firm handles information submitted through this website.</p>
  <h2>Information we collect</h2><p>When you request a call, we collect your name, phone number, optional email address, preferred contact time, the answers you select in the three-question intake, consent status, and technical information used to protect the form from abuse. We do not ask for medical records, Social Security numbers, financial account numbers, or a detailed case narrative through this form.</p>
  <h2>How we use it</h2><p>We use inquiry information to return your call, review whether the firm may be able to help, complete a conflicts check when appropriate, prevent fraud or abuse, maintain site security, and comply with legal and professional obligations. Sending information does not create an attorney-client relationship.</p>
  <h2>Service providers</h2><p>Cloudflare Turnstile processes limited device and request information for bot prevention. Resend processes and delivers inquiry emails. Our hosting and network providers process technical logs needed to operate and secure the website. These providers may process information only to provide their services, protect their systems, or comply with law.</p>
  <h2>Sharing and selling</h2><p>We do not sell personal information or share it for cross-context behavioral advertising. We may disclose information to service providers, professional advisers, or authorities when reasonably necessary to operate the site, protect rights and safety, investigate misuse, or comply with law. If another lawyer or firm may be better suited to help, we will ask before sending them information that identifies you.</p>
  <h2>Retention</h2><p>Website inquiries that do not become client matters are ordinarily kept for up to 24 months, then deleted or de-identified, unless a longer period is reasonably needed for conflicts records, legal obligations, fraud prevention, a dispute, or your request. Client-file retention is governed by the engagement agreement and the firm’s client-record policies.</p>
  <h2>Cookies and browser signals</h2><p>This site uses only technologies reasonably necessary to operate and secure the site, including Turnstile. We do not currently use behavioral advertising or analytics cookies. Because we do not track visitors across unrelated websites, “Do Not Track” and Global Privacy Control signals do not change the site’s current behavior.</p>
  <h2>Your choices</h2><p>You may call instead of using the form. Subject to applicable law, you may ask to know, correct, or delete information connected to a website inquiry. We may need to verify your identity and may retain limited information when required for legal, ethical, security, or conflicts purposes. Call <a href={lawPhoneHref}>{lawPhoneDisplay}</a> or email <a href="mailto:hello.rarescore@gmail.com?subject=Privacy%20request">hello.rarescore@gmail.com</a>.</p>
  <h2>Security and children</h2><p>We use reasonable administrative and technical safeguards, but no internet transmission is completely secure. Do not send confidential or time-sensitive documents through the website. This site is not directed to children under 13, and we do not knowingly collect their information through the intake form.</p>
  <h2>Changes</h2><p>We may update this policy as the site or our practices change. The effective date above identifies the current version.</p>
  </main>; }
