"use client";
import { useMemo, useState } from "react";
import { ToolFrame, downloadRecord } from "./tool-shared";
import Link from "next/link";
import { plumbingBase } from "../data";
import { useSystemLens } from "@/features/system-lens/system-lens-store";

type Passport = { year: string; supply: string; drain: string; heater: string; heaterAge: string; baths: string; shutoff: string; observations: string[] };
const start: Passport = { year: "", supply: "unknown", drain: "unknown", heater: "tank-gas", heaterAge: "unknown", baths: "2", shutoff: "unknown", observations: [] };
const steps = ["Property", "Materials", "Equipment", "Shutoffs + observations", "Owner record"];

export default function PassportTool() {
  const [step, setStep] = useState(0); const [data, setData] = useState(start); const [photoCount, setPhotoCount] = useState(0); const record = useSystemLens((state) => state.record);
  const questions = useMemo(() => { const list = []; const year = Number(data.year); if (!year) list.push("Confirm approximate construction year and major plumbing renovation dates."); if (data.supply === "unknown") list.push("Identify visible supply material at an accessible location."); if (data.drain === "unknown") list.push("Identify visible drain material and known cleanout access."); if (data.heaterAge === "unknown" || Number(data.heaterAge) >= 10) list.push("Review water-heater age, manufacturer maintenance, condition, and replacement planning."); if (data.shutoff !== "known") list.push("Locate and document the main water shutoff with qualified help if needed."); if (data.observations.length) list.push("Discuss the recorded observations without assuming a diagnosis."); return list; }, [data]);
  function update(key: keyof Passport, value: string | string[] | undefined) { if (value === undefined) return; setData((current) => ({ ...current, [key]: value })); }
  function next() { const nextStep = Math.min(4, step + 1); setStep(nextStep); if (step === 0) record({ scope: "plumbing", type: "passport_started", signal: "Plumbing Passport started", response: "Private property record opened", value: "A useful owner asset before lead capture", status: "observed" }); if (nextStep === 4) record({ scope: "plumbing", type: "risk_questions_derived", signal: "Property record completed", response: "Inspection questions and maintenance record prepared", value: "More qualified long-term service context", status: "derived" }); }
  const output = `LEV & ON HOME SERVICES — WHOLE-HOME PLUMBING PASSPORT\nFictional demonstration · Owner-held draft\n\nPROPERTY\nApproximate year: ${data.year || "Unknown"}\nBathrooms: ${data.baths}\n\nSYSTEMS\nSupply material: ${data.supply}\nDrain material: ${data.drain}\nWater heating: ${data.heater}\nEquipment age: ${data.heaterAge}\nMain shutoff: ${data.shutoff}\n\nOWNER OBSERVATIONS\n${data.observations.length ? data.observations.map((item) => `- ${item}`).join("\n") : "- None recorded"}\n\nPROFESSIONAL REVIEW QUESTIONS\n- ${questions.join("\n- ")}\n\nLIMITS\nThis is a homeowner-entered demonstration record, not an inspection, diagnosis, maintenance prescription, code review, or guarantee. Verify all details onsite. Manufacturer instructions, permits, applicable code, licensed review, and the authority having jurisdiction take precedence. This record may reveal sensitive property infrastructure; store and share it carefully.`;
  return <ToolFrame eyebrow="Tool 01 / Signature property record" title="Whole-Home Plumbing Passport" intro="Build a private, downloadable record of known materials, equipment, fixtures, shutoffs, observations, and professional-review questions."><div className="pl-passport-progress"><span>{steps[step]}</span><strong>{step + 1} of {steps.length}</strong><div><i style={{ transform: `scaleX(${(step + 1) / steps.length})` }} /></div></div><div className="pl-passport-layout"><form className="pl-tool-form" onSubmit={(event) => { event.preventDefault(); next(); }}>
    {step === 0 && <fieldset><legend>Property starting point</legend><div className="pl-form-grid"><label>Approximate construction year<input value={data.year} onChange={(event) => update("year", event.target.value)} inputMode="numeric" placeholder="I don’t know" /></label><label>Bathrooms<input type="number" min="1" max="20" value={data.baths} onChange={(event) => update("baths", event.target.value)} /></label></div><p className="pl-field-help">Unknown is a valid answer. This tool should never force false precision.</p></fieldset>}
    {step === 1 && <fieldset><legend>Visible or documented materials</legend><div className="pl-form-grid"><label>Supply material<select value={data.supply} onChange={(event) => update("supply", event.target.value)}><option value="unknown">I don’t know</option><option>Copper</option><option>PEX</option><option>Galvanized steel</option><option>Mixed / altered</option></select></label><label>Drain material<select value={data.drain} onChange={(event) => update("drain", event.target.value)}><option value="unknown">I don’t know</option><option>Cast iron</option><option>ABS / PVC</option><option>Clay</option><option>Mixed / altered</option></select></label></div><p className="pl-field-help">Do not enter crawlspaces, open walls, or handle questionable materials to answer.</p></fieldset>}
    {step === 2 && <fieldset><legend>Water-heating equipment</legend><div className="pl-form-grid"><label>System type<select value={data.heater} onChange={(event) => update("heater", event.target.value)}><option value="tank-gas">Tank · gas</option><option value="tank-electric">Tank · electric</option><option value="tankless">Tankless</option><option value="heat-pump">Heat pump</option><option value="unknown">I don’t know</option></select></label><label>Approximate equipment age<select value={data.heaterAge} onChange={(event) => update("heaterAge", event.target.value)}><option value="unknown">I don’t know</option><option value="2">0–4 years</option><option value="7">5–9 years</option><option value="12">10–14 years</option><option value="16">15+ years</option></select></label></div></fieldset>}
    {step === 3 && <><fieldset><legend>Main water shutoff</legend><div className="pl-choice-row">{[["known", "Known + accessible"], ["limited", "Known, limited access"], ["unknown", "I don’t know"]].map(([value, label]) => <label key={value}><input type="radio" checked={data.shutoff === value} onChange={() => update("shutoff", value)} /><span>{label}</span></label>)}</div></fieldset><fieldset><legend>Owner observations</legend><div className="pl-check-grid">{["Recurring leak", "Pressure change", "Hot-water change", "Drain recurrence", "Visible corrosion", "Prior unrecorded work"].map((item) => <label key={item}><input type="checkbox" checked={data.observations.includes(item)} onChange={(event) => update("observations", event.target.checked ? [...data.observations, item] : data.observations.filter((value) => value !== item))} /><span>{item}</span></label>)}</div></fieldset><label className="pl-upload">Reference photos <span>local count only</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(event) => { const count = Math.min(6, Array.from(event.target.files ?? []).filter((file) => file.size <= 8_000_000).length); setPhotoCount(count); if (count) record({ scope: "plumbing", type: "photo_context_added", signal: "Passport reference photos selected", response: "Local-only context added", value: "Richer record without exposing filenames", status: "observed" }); }} /><small>{photoCount ? `${photoCount} files selected locally. ` : ""}Nothing is uploaded, stored, or included in the text download.</small></label></>}
    {step < 4 && <div className="pl-tool-nav">{step > 0 && <button className="pl-button" type="button" onClick={() => setStep((value) => value - 1)}>Back</button>}<button className="pl-button pl-button--primary" type="submit">{step === 3 ? "Build owner record" : "Continue"}</button></div>}
    {step === 4 && <section className="pl-passport-result" aria-live="polite"><p className="pl-eyebrow">Owner record ready</p><h2>Your professional-review questions</h2><ol>{questions.map((question) => <li key={question}>{question}</li>)}</ol><div className="pl-passport-systems"><div><span>Supply</span><strong>{data.supply}</strong></div><div><span>Drainage</span><strong>{data.drain}</strong></div><div><span>Water heating</span><strong>{data.heater}</strong></div><div><span>Main shutoff</span><strong>{data.shutoff}</strong></div></div><p className="pl-privacy-note">This record may reveal sensitive property infrastructure. Store and share it carefully.</p><div className="pl-inline-actions"><button className="pl-button" type="button" onClick={() => downloadRecord("whole-home-plumbing-passport.txt", output)}>Download owner record</button><Link className="pl-button pl-button--primary" href={`${plumbingBase}/request-service?service=not-sure`}>Discuss this record</Link><button className="pl-button" type="button" onClick={() => setStep(0)}>Edit answers</button></div></section>}
  </form><aside className="pl-passport-summary"><p>RECORD / LIVE</p><dl><div><dt>Property</dt><dd>{data.year || "Unknown year"} · {data.baths} bath</dd></div><div><dt>Materials</dt><dd>{data.supply} / {data.drain}</dd></div><div><dt>Equipment</dt><dd>{data.heater}</dd></div><div><dt>Shutoff</dt><dd>{data.shutoff}</dd></div><div><dt>Observations</dt><dd>{data.observations.length || "None recorded"}</dd></div></dl><small>Draft stays in browser memory and clears on refresh.</small></aside></div></ToolFrame>;
}
