import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";

test("required production routes, media, and lead pipeline exist",()=>{for(const file of ["src/app/(law)/page.tsx","src/app/(law)/actions.ts","src/app/(law)/consultation/page.tsx","src/app/(law)/practice-areas/[slug]/page.tsx","src/app/(law)/resources/[slug]/page.tsx","src/app/(law)/privacy/page.tsx","src/app/not-found.tsx","src/lib/intake/email.ts","public/media/scroll/manifest.json",".env.example"])assert.ok(existsSync(file),`${file} is missing`);});
test("scroll media and reversible intake controls are present",()=>{for(const file of ["public/media/scroll/manifest.json","public/media/scroll/crash/frame-000.webp","public/media/scroll/crash/frame-018.webp","public/media/scroll/evidence-network/frame-025.webp","public/media/scroll/uncertainty-cloud/frame-029.webp","public/media/scroll/forward-vortex/frame-033.webp"])assert.ok(existsSync(file),`${file} is missing`);const hero=readFileSync("src/features/demos/injury-law/home-hero.client.tsx","utf8");const page=readFileSync("src/app/(law)/page.tsx","utf8");assert.match(hero,/sequence="crash"/);for(const sequence of ["evidence-network","uncertainty-cloud","forward-vortex"])assert.match(page,new RegExp(`sequence="${sequence}"`),`${sequence} scroll story is missing`);for(const label of ["Edit answers","Restart","← Back","Change"])assert.match(hero,new RegExp(label),`${label} control is missing`);});
test("intake failures provide a visible telephone fallback",()=>{const form=readFileSync("src/features/demos/injury-law/consultation-form.client.tsx","utf8");const action=readFileSync("src/app/(law)/actions.ts","utf8");assert.match(form,/Online requests are temporarily unavailable/);assert.match(form,/Your answers are still here/);assert.match(action,/Your information was not sent/);});
test("inquiries use the approved email-only destination",()=>{const email=readFileSync("src/lib/intake/email.ts","utf8");const action=readFileSync("src/app/(law)/actions.ts","utf8");assert.match(email,/hello\.rarescore@gmail\.com/);assert.doesNotMatch(action,/DATABASE_URL|neon|postgres/i);});
function sourceFiles(directory){return readdirSync(directory,{withFileTypes:true}).flatMap(entry=>{const path=join(directory,entry.name);return entry.isDirectory()?sourceFiles(path):/\.(tsx?|css)$/.test(entry.name)?[path]:[];});}
test("production source has no legacy brand or unfinished markers",()=>{for(const file of sourceFiles("src")){const source=readFileSync(file,"utf8");assert.doesNotMatch(source,/Morrow|Vale|System Lens|demo-preview/i,`${file} contains legacy copy`);assert.doesNotMatch(source,/href\s*=\s*["']#["']/,`${file} has an inert hash link`);assert.doesNotMatch(source,/\b(?:TODO|FIXME)\b/,`${file} has an unfinished marker`);}});
