"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useSystemLens } from "@/features/system-lens/system-lens-store";
import { listings, neighborhoods, realEstateBase } from "./data";
import { useRealEstateStore } from "./real-estate-store";
import { compareOffer, currency, monthlyHousingCost, sellerNet } from "./tool-engines";

export type RealEstateToolSlug = "move-strategy-studio" | "offer-comparison" | "true-monthly-cost" | "seller-readiness" | "tour-builder" | "neighborhood-comparison";

function ResultActions({ title, text }: { title: string; text: string }) {
  function download() {
    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob); link.download = `${title.toLowerCase().replaceAll(" ", "-")}.txt`; link.click();
    URL.revokeObjectURL(link.href);
  }
  return <div className="re-result-actions"><button type="button" onClick={download}>Download plan</button><button type="button" onClick={() => window.print()}>Print result</button><Link href={`${realEstateBase}/consultation`}>Discuss this result</Link></div>;
}

export function RealEstateTool({ slug }: { slug: RealEstateToolSlug }) {
  if (slug === "move-strategy-studio") return <MoveStrategy />;
  if (slug === "offer-comparison") return <OfferComparison />;
  if (slug === "true-monthly-cost") return <MonthlyCost />;
  if (slug === "seller-readiness") return <SellerReadiness />;
  if (slug === "tour-builder") return <TourBuilder />;
  return <NeighborhoodComparison />;
}

function MoveStrategy() {
  const [goal, setGoal] = useState<"buy" | "sell" | "both">("both");
  const [timing, setTiming] = useState("3-6 months");
  const [value, setValue] = useState(1500000);
  const [payoff, setPayoff] = useState(650000);
  const [budget, setBudget] = useState(1800000);
  const [financing, setFinancing] = useState("Pre-approval not started");
  const [condition, setCondition] = useState("Some preparation needed");
  const [priority, setPriority] = useState("Avoid temporary housing");
  const [complete, setComplete] = useState(false);
  const record = useSystemLens((state) => state.record);
  const includesSale = goal !== "buy";
  const net = sellerNet({ salePrice: value, payoff, transactionRate: 6, concessions: 10000, repairs: condition === "Ready now" ? 5000 : 25000, closingCosts: 12000 });
  const plan = [
    { horizon: "Next 30 days", actions: [goal !== "sell" ? "Confirm financing path and a comfortable all-in monthly range." : "Document property condition and decide what requires professional review.", includesSale ? "Establish an illustrative net range using explicit cost assumptions." : "Build a property brief around location, condition, and daily use.", `Protect the priority: ${priority.toLowerCase()}.`] },
    { horizon: "Days 31–60", actions: [includesSale ? "Sequence preparation, photography, and launch timing." : "Start a focused property search and tour only qualified options.", goal === "both" ? "Compare buy-first and sell-first paths against housing, financing, and timing constraints." : "Review the next decision checkpoint with your advisor."] },
    { horizon: "Days 61–90", actions: [goal === "sell" ? "Review offer terms and execution risk alongside estimated net." : "Prepare offer boundaries, diligence questions, and close logistics.", "Confirm the working move date, handoff plan, and next conversation."] },
  ];
  const resultText = `MOVE STRATEGY STUDIO — DEMONSTRATION\nGoal: ${goal}\nTiming: ${timing}\nFinancing: ${financing}\nCondition: ${condition}\nPriority: ${priority}\n${goal !== "sell" ? `Target purchase budget: ${currency(budget)}\n` : ""}${includesSale ? `Illustrative estimated net: ${currency(net.net)}\nAssumptions: sale price ${currency(value)}, payoff ${currency(payoff)}, 6% user-adjustable transaction-cost placeholder, $10,000 concessions, ${condition === "Ready now" ? "$5,000" : "$25,000"} preparation, $12,000 closing/transfer placeholder.\n` : ""}\n${plan.map((item) => `${item.horizon}:\n- ${item.actions.join("\n- ")}`).join("\n\n")}\n\nEducational sample only. Verify property, tax, financing, service costs, and legal obligations with qualified professionals.`;

  if (complete) return <section className="re-tool-result" aria-live="polite"><p className="re-kicker">Your working move brief</p><h2>{timing} becomes a sequence.</h2>{goal !== "sell" ? <p className="re-plan-assumption">Target purchase budget: <strong>{currency(budget)}</strong></p> : null}<div className="re-plan-grid">{plan.map((item) => <article key={item.horizon}><h3>{item.horizon}</h3><ul>{item.actions.map((action) => <li key={action}>{action}</li>)}</ul></article>)}</div>{includesSale ? <div className="re-net"><div><p>Illustrative estimated net</p><strong>{currency(net.net)}</strong></div><dl><div><dt>Sale-price assumption</dt><dd>{currency(value)}</dd></div><div><dt>Loan payoff</dt><dd>− {currency(payoff)}</dd></div><div><dt>Transaction-cost placeholder (6%)</dt><dd>− {currency(net.transactionCosts)}</dd></div><div><dt>Concessions / preparation / closing</dt><dd>− {currency(10000 + (condition === "Ready now" ? 5000 : 25000) + 12000)}</dd></div></dl></div> : null}<div className="re-paths"><div><h3>Buy first</h3><p>May preserve access to the right property, but can increase carrying cost and financing complexity.</p></div><div><h3>Sell first</h3><p>Clarifies available proceeds, but can create timing pressure or temporary-housing needs.</p></div></div><p className="re-tool-limit">This is an educational sample plan, not financial, tax, legal, appraisal, or lending advice. Assumptions are visible so they can be replaced with verified figures.</p><button className="re-button" type="button" onClick={() => setComplete(false)}>Edit answers</button><ResultActions title="Move Strategy Plan" text={resultText} /></section>;

  return <form className="re-tool-form re-tool-form--studio" onSubmit={(event) => { event.preventDefault(); setComplete(true); record({ type: "tool_completed", signal: "Move plan completed", response: "Buying/selling intent and timing summarized without raw financial values", value: "A 30/60/90-day conversation brief is ready", status: "derived" }); }}><fieldset><legend>What are you planning?</legend><div className="re-choice-row">{(["buy", "sell", "both"] as const).map((item) => <label key={item}><input type="radio" name="goal" checked={goal === item} onChange={() => setGoal(item)} /><span>{item === "both" ? "Buy and sell" : item === "buy" ? "Buy" : "Sell"}</span></label>)}</div></fieldset><div className="re-tool-fields"><label>Desired timing<select value={timing} onChange={(e) => setTiming(e.target.value)}><option>0-3 months</option><option>3-6 months</option><option>6-12 months</option><option>Exploring</option></select></label>{includesSale ? <><label>Estimated current property value<input type="number" min="0" value={value} onChange={(e) => setValue(Number(e.target.value))} /></label><label>Approximate loan payoff<input type="number" min="0" value={payoff} onChange={(e) => setPayoff(Number(e.target.value))} /></label><label>Property condition<select value={condition} onChange={(e) => setCondition(e.target.value)}><option>Ready now</option><option>Some preparation needed</option><option>Significant work to assess</option></select></label></> : null}{goal !== "sell" ? <><label>Target purchase budget<input type="number" min="0" value={budget} onChange={(e) => setBudget(Number(e.target.value))} /></label><label>Financing preparation<select value={financing} onChange={(e) => setFinancing(e.target.value)}><option>Pre-approval not started</option><option>Speaking with a lender</option><option>Pre-approved</option><option>Cash purchase under consideration</option></select></label></> : null}<label>Most important constraint<select value={priority} onChange={(e) => setPriority(e.target.value)}><option>Avoid temporary housing</option><option>Minimize carrying overlap</option><option>Preserve flexibility</option><option>Move by a fixed date</option><option>Prioritize the right property</option></select></label></div><p className="re-tool-limit">Private financial inputs stay in this browser’s memory only. They are not placed in the URL, analytics, System Lens, or local storage.</p><button className="re-button re-button--solid" type="submit">Build my 30 / 60 / 90 plan <span aria-hidden="true">→</span></button></form>;
}

type OfferInput = { price: number; concessions: number; otherCosts: number; financing: string; contingencyDays: number; closeDays: number };
function OfferComparison() {
  const [a, setA] = useState<OfferInput>({ price: 1800000, concessions: 0, otherCosts: 12000, financing: "conventional", contingencyDays: 12, closeDays: 30 });
  const [b, setB] = useState<OfferInput>({ price: 1775000, concessions: 5000, otherCosts: 8000, financing: "cash", contingencyDays: 7, closeDays: 21 });
  const [complete, setComplete] = useState(false); const record = useSystemLens((state) => state.record);
  const results = [compareOffer(a), compareOffer(b)];
  const resultA = results[0]!;
  const resultB = results[1]!;
  const editor = (label: string, value: OfferInput, set: (value: OfferInput) => void) => <fieldset><legend>{label}</legend><label>Purchase price<input type="number" min="0" value={value.price} onChange={(e) => set({ ...value, price: Number(e.target.value) })} /></label><label>Seller concessions<input type="number" min="0" value={value.concessions} onChange={(e) => set({ ...value, concessions: Number(e.target.value) })} /></label><label>Other seller costs<input type="number" min="0" value={value.otherCosts} onChange={(e) => set({ ...value, otherCosts: Number(e.target.value) })} /></label><label>Financing<select value={value.financing} onChange={(e) => set({ ...value, financing: e.target.value })}><option value="conventional">Conventional</option><option value="jumbo">Jumbo</option><option value="cash">Cash</option></select></label><label>Contingency period (days)<input type="number" min="0" value={value.contingencyDays} onChange={(e) => set({ ...value, contingencyDays: Number(e.target.value) })} /></label><label>Close timeline (days)<input type="number" min="0" value={value.closeDays} onChange={(e) => set({ ...value, closeDays: Number(e.target.value) })} /></label></fieldset>;
  if (complete) return <section className="re-tool-result" aria-live="polite"><p className="re-kicker">Transparent comparison</p><h2>Two offers. No hidden winner score.</h2><div className="re-comparison-table"><table><thead><tr><th>Factor</th><th>Offer A</th><th>Offer B</th></tr></thead><tbody><tr><th>Price</th><td>{currency(a.price)}</td><td>{currency(b.price)}</td></tr><tr><th>Estimated net before payoff</th><td>{currency(resultA.estimatedNet)}</td><td>{currency(resultB.estimatedNet)}</td></tr><tr><th>Financing</th><td>{a.financing}</td><td>{b.financing}</td></tr><tr><th>Contingency</th><td>{a.contingencyDays} days</td><td>{b.contingencyDays} days</td></tr><tr><th>Close</th><td>{a.closeDays} days</td><td>{b.closeDays} days</td></tr><tr><th>Reliability considerations</th><td>{resultA.considerations.join("; ")}</td><td>{resultB.considerations.join("; ")}</td></tr></tbody></table></div><p className="re-tool-limit">Estimated net excludes loan payoff, taxes, transfer/escrow/title details, repairs, prorations, and transaction services not entered. Verify all terms and costs.</p><button className="re-button" type="button" onClick={() => setComplete(false)}>Edit offers</button></section>;
  return <form className="re-tool-form" onSubmit={(event) => { event.preventDefault(); setComplete(true); record({ type: "tool_completed", signal: "Two offers compared", response: "Terms and reliability factors organized", value: "Offer review can focus on tradeoffs, not price alone", status: "derived" }); }}><div className="re-offer-editors">{editor("Offer A", a, setA)}{editor("Offer B", b, setB)}</div><button className="re-button re-button--solid" type="submit">Compare offers <span aria-hidden="true">→</span></button></form>;
}

function MonthlyCost() {
  const [input, setInput] = useState({ price: 1500000, downPayment: 300000, rate: 6.5, years: 30, taxRate: 1.25, annualInsurance: 4800, hoa: 0, maintenanceRate: 1 });
  const [complete, setComplete] = useState(false); const record = useSystemLens((state) => state.record); const result = monthlyHousingCost(input);
  if (complete) return <section className="re-tool-result" aria-live="polite"><p className="re-kicker">Illustrative monthly ownership range</p><h2>{currency(result.total)} <small>/ month</small></h2><div className="re-cost-breakdown">{Object.entries(result).filter(([key]) => key !== "total").map(([key, value]) => <div key={key}><span>{key === "mortgage" ? "Principal & interest" : key === "tax" ? "Property tax" : key === "insurance" ? "Insurance" : key === "hoa" ? "HOA" : "Maintenance allowance"}</span><b>{currency(value)}</b></div>)}</div><p className="re-tool-limit">Assumes {input.years}-year financing at {input.rate}%, {input.taxRate}% annual property tax, {currency(input.annualInsurance)} annual insurance, and {input.maintenanceRate}% annual maintenance. Excludes mortgage insurance, utilities, closing costs, assessments, and rate changes. Not a lending quote.</p><button className="re-button" type="button" onClick={() => setComplete(false)}>Edit assumptions</button></section>;
  return <form className="re-tool-form" onSubmit={(event) => { event.preventDefault(); setComplete(true); record({ type: "tool_completed", signal: "Monthly ownership estimate completed", response: "Cost categories and assumptions organized", value: "Budget conversation can include more than the mortgage", status: "derived" }); }}><div className="re-tool-fields"><label>Purchase price<input type="number" min="0" value={input.price} onChange={(e) => setInput({ ...input, price: Number(e.target.value) })} /></label><label>Down payment<input type="number" min="0" value={input.downPayment} onChange={(e) => setInput({ ...input, downPayment: Number(e.target.value) })} /></label><label>Interest rate (%)<input type="number" min="0" step="0.01" value={input.rate} onChange={(e) => setInput({ ...input, rate: Number(e.target.value) })} /></label><label>Loan term<select value={input.years} onChange={(e) => setInput({ ...input, years: Number(e.target.value) })}><option value="30">30 years</option><option value="15">15 years</option></select></label><label>Annual property tax (%)<input type="number" min="0" step="0.01" value={input.taxRate} onChange={(e) => setInput({ ...input, taxRate: Number(e.target.value) })} /></label><label>Annual insurance<input type="number" min="0" value={input.annualInsurance} onChange={(e) => setInput({ ...input, annualInsurance: Number(e.target.value) })} /></label><label>Monthly HOA<input type="number" min="0" value={input.hoa} onChange={(e) => setInput({ ...input, hoa: Number(e.target.value) })} /></label><label>Annual maintenance allowance (%)<input type="number" min="0" step="0.1" value={input.maintenanceRate} onChange={(e) => setInput({ ...input, maintenanceRate: Number(e.target.value) })} /></label></div><button className="re-button re-button--solid" type="submit">Calculate true monthly cost <span aria-hidden="true">→</span></button></form>;
}

function SellerReadiness() {
  const [condition, setCondition] = useState("lived-in"); const [timing, setTiming] = useState("3-6 months"); const [items, setItems] = useState<string[]>([]); const [complete, setComplete] = useState(false); const record = useSystemLens((state) => state.record);
  const options = ["Known roof or drainage question", "Aging mechanical systems", "Interior paint or patching", "Landscape cleanup", "Storage and editing", "Permit/document review"];
  const priorities = [...(items.includes("Known roof or drainage question") ? ["Ask a qualified professional to assess water-management conditions before cosmetic work."] : []), ...(items.includes("Aging mechanical systems") ? ["Document age, service history, and known performance of major systems."] : []), ...(items.includes("Permit/document review") ? ["Assemble permits, plans, warranties, and material property records."] : []), "Walk the property with the likely buyer questions in mind.", condition === "project" ? "Separate safety/condition work from optional presentation improvements." : "Prioritize cleaning, editing, light repair, and photography readiness.", `Work backward from a ${timing} desired launch window.`];
  if (complete) return <section className="re-tool-result" aria-live="polite"><p className="re-kicker">Seller readiness report</p><h2>Do the work that reduces uncertainty first.</h2><ol className="re-priority-list">{priorities.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span><p>{item}</p></li>)}</ol><p className="re-tool-limit">This plan does not predict return on investment or replace inspections, contractor scopes, permits, or local disclosure advice.</p><button className="re-button" type="button" onClick={() => setComplete(false)}>Edit property brief</button></section>;
  return <form className="re-tool-form" onSubmit={(event) => { event.preventDefault(); setComplete(true); record({ type: "seller_intent", signal: "Seller readiness brief completed", response: "Preparation topics prioritized", value: "First conversation begins with property context", status: "derived" }); }}><div className="re-tool-fields"><label>Current condition<select value={condition} onChange={(e) => setCondition(e.target.value)}><option value="ready">Recently updated / ready</option><option value="lived-in">Lived-in with light preparation</option><option value="project">Several condition questions to assess</option></select></label><label>Desired market timing<select value={timing} onChange={(e) => setTiming(e.target.value)}><option>0-3 months</option><option>3-6 months</option><option>6-12 months</option><option>Exploring</option></select></label></div><fieldset><legend>Topics already on your mind</legend><div className="re-check-list">{options.map((item) => <label key={item}><input type="checkbox" checked={items.includes(item)} onChange={() => setItems((state) => state.includes(item) ? state.filter((value) => value !== item) : [...state, item])} /><span>{item}</span></label>)}</div></fieldset><button className="re-button re-button--solid" type="submit">Prioritize preparation <span aria-hidden="true">→</span></button></form>;
}

function TourBuilder() {
  const tour = useRealEstateStore((state) => state.tour); const toggleTour = useRealEstateStore((state) => state.toggleTour); const moveTour = useRealEstateStore((state) => state.moveTour); const [date, setDate] = useState(""); const [time, setTime] = useState("Morning"); const [prepared, setPrepared] = useState(false); const record = useSystemLens((state) => state.record);
  const selected = tour.map((slug) => listings.find((listing) => listing.slug === slug)).filter(Boolean);
  return <section className="re-tour-builder">{prepared ? <div className="re-tool-result" role="status"><p className="re-kicker">Tour request prepared · Demonstration</p><h2>{selected.length} {selected.length === 1 ? "property" : "properties"} in one working route.</h2><p>Preferred timing: {date || "Date not selected"}, {time.toLowerCase()}. No showing request was sent. In production, the selected property IDs and timing would enter a coordinated scheduling workflow.</p><button className="re-button" type="button" onClick={() => setPrepared(false)}>Edit tour</button><Link className="re-button re-button--solid" href={`${realEstateBase}/consultation?intent=buying`}>Add contact context</Link></div> : <><div className="re-tour-list">{selected.length ? selected.map((listing, index) => listing && <article key={listing.slug}><span>{String(index + 1).padStart(2, "0")}</span><div><h2>{listing.address}</h2><p>{listing.neighborhood} · {listing.type}</p></div><div><button type="button" disabled={index === 0} onClick={() => moveTour(listing.slug, -1)}>Move up</button><button type="button" disabled={index === selected.length - 1} onClick={() => moveTour(listing.slug, 1)}>Move down</button><button type="button" onClick={() => toggleTour(listing.slug)}>Remove</button></div></article>) : <div className="re-empty"><h2>Your tour is empty.</h2><p>Add sample properties from search or a listing page, then return here to order and prepare the request.</p><Link className="re-button" href={`${realEstateBase}/listings`}>Open property search</Link></div>}</div>{selected.length ? <form className="re-tool-form re-tour-time" onSubmit={(event) => { event.preventDefault(); if (!date) return; setPrepared(true); record({ type: "showing_request", signal: "Tour timing selected", response: "Property IDs and preferred window bundled", value: "A coordinated scheduling request is ready", status: "demo-preview" }); }}><label>Preferred date<input type="date" value={date} onInput={(e) => setDate(e.currentTarget.value)} required /></label><label>Preferred time<select value={time} onChange={(e) => setTime(e.target.value)}><option>Morning</option><option>Midday</option><option>Afternoon</option></select></label><button className="re-button re-button--solid" type="submit">Prepare tour request</button></form> : null}</>}</section>;
}

function NeighborhoodComparison() {
  const [left, setLeft] = useState(neighborhoods[0]?.slug ?? ""); const [right, setRight] = useState(neighborhoods[1]?.slug ?? ""); const record = useSystemLens((state) => state.record);
  const a = neighborhoods.find((item) => item.slug === left); const b = neighborhoods.find((item) => item.slug === right);
  const rows = useMemo(() => a && b ? [["Housing", a.housing, b.housing], ["Architecture", a.architecture, b.architecture], ["Sample price range", a.priceRange, b.priceRange], ["Access", a.access, b.access], ["Parks / open space", a.parks, b.parks], ["Daily services", a.dailyLife, b.dailyLife]] : [], [a, b]);
  return <section className="re-neighborhood-compare"><div className="re-compare-selectors"><label>First area<select value={left} onChange={(e) => { setLeft(e.target.value); record({ type: "search_intent", signal: "Neighborhood comparison adjusted", response: "Objective place criteria kept together", value: "Location conversation can focus on observable tradeoffs", status: "derived" }); }}>{neighborhoods.map((area) => <option key={area.slug} value={area.slug}>{area.name}</option>)}</select></label><label>Second area<select value={right} onChange={(e) => setRight(e.target.value)}>{neighborhoods.map((area) => <option key={area.slug} value={area.slug}>{area.name}</option>)}</select></label></div>{a && b ? <div className="re-comparison-table"><table><caption>Objective sample comparison · Observed August 2026</caption><thead><tr><th>Criterion</th><th>{a.name}</th><th>{b.name}</th></tr></thead><tbody>{rows.map(([label, first, second]) => <tr key={label}><th>{label}</th><td>{first}</td><td>{second}</td></tr>)}</tbody></table></div> : null}<p className="re-tool-limit">No demographics, protected characteristics, school rankings, safety scores, or coded recommendations are used. Verify current property, transit, municipal, and market sources.</p></section>;
}
