import { notFound } from "next/navigation";
import { InjuryCta, InjuryPageIntro } from "@/features/demos/injury-law/injury-layout";
import { getPracticeArea, injuryBase, practiceAreas } from "@/features/demos/injury-law/data";

export function generateStaticParams(){return practiceAreas.map(({slug})=>({slug}));}
export default async function Page({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;const area=getPracticeArea(slug);if(!area)notFound();
  return <main id="injury-main"><InjuryPageIntro eyebrow="Practice area · General information" title={area.name}><p>{area.short} These are general orientation points, not a legal conclusion about a specific matter.</p></InjuryPageIntro><section className="il-section"><div className="il-shell il-content-grid"><aside className="il-annotation"><strong>Why this matters</strong>Early care and preservation decisions can be easier to make before records are scattered. Deadlines and duties vary by jurisdiction.</aside><article className="il-prose"><section><h2>What to do first</h2><ul className="il-record-list">{area.firstSteps.map((item)=><li key={item}>{item}</li>)}</ul></section><section><h2>Records that may help</h2><p>Preserve originals and work from copies. Do not place sensitive evidence into this public demonstration.</p><ul className="il-record-list">{area.records.map((item)=><li key={item}>{item}</li>)}</ul></section><section><h2>What an attorney may review</h2><ul className="il-record-list">{area.review.map((item)=><li key={item}>{item}</li>)}</ul><p>What matters legally depends on facts, law, jurisdiction, and evidence. No page can decide whether someone has a case or calculate a deadline.</p></section></article></div></section><InjuryCta title="Turn scattered details into a review outline." copy="The guided review keeps answers in page memory, gives an action plan first, and never estimates a case value." href={`${injuryBase}/case-review`} label="Open Incident & Impact Review" /></main>;
}
