import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { AlertTriangle, ArrowRight, Check, ChevronRight, Globe2, Info, LoaderCircle, LockKeyhole, Search, ShieldCheck, Wrench } from 'lucide-react'
import Seo from '../components/Seo'
import { SectionIntro } from '../components/UI'

const categories=['Metadata','Structure','Crawlability','Mobile','Media','Trust']
const previewIssues=[
  {severity:'high',title:'Live crawler is not connected in local preview',detail:'Deploy the included serverless API to run a factual crawl of the submitted URL.',fix:'Deploy on Vercel and the same form becomes a live audit.'},
  {severity:'medium',title:'Ranking data requires verified access',detail:'A public page crawl cannot truthfully know every query and position for a domain.',fix:'Connect Google Search Console during onboarding for real query data.'},
]

function ScoreRing({score}){return <div className="score-ring" style={{'--score':score}}><div><b>{score}</b><span>/100</span></div></div>}

export default function Audit(){
 const [url,setUrl]=useState(''); const [email,setEmail]=useState(''); const [state,setState]=useState('idle'); const [result,setResult]=useState(null); const [error,setError]=useState('')
 const valid=useMemo(()=>{try{const u=new URL(/^https?:\/\//.test(url)?url:`https://${url}`);return !!u.hostname.includes('.')}catch{return false}},[url])
 async function run(e){e.preventDefault();if(!valid){setError('Enter a valid public website, such as example.com.');return}setError('');setState('loading');
   try{const response=await fetch('/api/audit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,email})});const data=await response.json();if(!response.ok)throw new Error(data.error||'We could not crawl that website.');setResult(data);setState('done')}
   catch(err){if(import.meta.env.DEV){setResult({url,score:64,mode:'preview',summary:'Local preview mode: deploy the included API for a factual live crawl.',categories:Object.fromEntries(categories.map((c,i)=>[c,[72,58,66,82,49,61][i]])),issues:previewIssues,estimate:{price:1850,label:'SEO remediation sprint',effort:'2–3 weeks'},checks:[]});setState('done')}else{setError(err.message);setState('idle')}}
 }
 return <><Seo title="Free Website SEO Audit | RS Marketing" description="Run a free live technical and on-page website audit. Get a transparent score, prioritized issues and a repair estimate from RS Marketing."/>
 <section className="audit-hero"><div className="wrap audit-hero-grid"><div><p className="eyebrow">Live technical preview</p><h1>Find what your website<br/><i>is making harder.</i></h1><p>We crawl one public page and evaluate the signals we can verify: metadata, headings, indexability, mobile setup, image markup, structured data and trust foundations.</p><div className="audit-trust"><span><ShieldCheck/> No password needed</span><span><LockKeyhole/> We do not store page content</span></div></div><form className="audit-form" onSubmit={run}><label>Website URL<input type="text" inputMode="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="yourwebsite.com" autoComplete="url" required/><Globe2/></label><label>Email for the report <span>(optional)</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com" autoComplete="email"/></label>{error&&<p className="form-error"><AlertTriangle/>{error}</p>}<button className="button button-acid" disabled={!valid||state==='loading'}>{state==='loading'?<><LoaderCircle className="spin"/> Crawling website…</>:<>Run free audit <ArrowRight/></>}</button><small>By running an audit, you agree to our <Link to="/privacy">privacy notice</Link>. We only inspect publicly available page data.</small></form></div></section>
 {state==='idle'&&<><section className="audit-method section"><div className="wrap"><SectionIntro eyebrow="What the score means" title={'A useful audit explains<br/><i>the consequence.</i>'} copy="A checklist without priority creates more work. Our scoring weights issues by their effect on discovery, comprehension and conversion."/><div className="method-grid">{[{n:'01',i:Search,t:'Crawl the evidence',p:'We request the public page and inspect the HTML and response signals it actually returns.'},{n:'02',i:Wrench,t:'Prioritize the defects',p:'Blocking and high-impact problems carry more weight than cosmetic recommendations.'},{n:'03',i:ChevronRight,t:'Map the repair',p:'The estimate reflects the number and difficulty of observed issues, not a made-up discount.'}].map(x=>{const I=x.i;return <article key={x.n}><span>{x.n}</span><I/><h2>{x.t}</h2><p>{x.p}</p></article>})}</div></div></section><section className="rank-limit"><div className="wrap"><Info/><div><h2>About “where you rank”</h2><p>A one-page public audit cannot truthfully identify every keyword position. Accurate ranking and query data requires location-specific rank tracking or verified Google Search Console access. We surface technical search readiness now and connect real query data during a client engagement.</p></div></div></section></>}
 {state==='done'&&result&&<AuditResults result={result}/>} 
 </>
}

function AuditResults({result}){const score=result.score||0;return <section className="audit-results section"><div className="wrap"><div className="result-head"><div><p className="eyebrow">Audit result</p><h2>{result.url}</h2><p>{result.summary}</p>{result.mode==='preview'&&<span className="preview-badge">LOCAL PREVIEW · NOT A LIVE SCORE</span>}</div><ScoreRing score={score}/></div>
 <div className="category-scores">{Object.entries(result.categories||{}).map(([name,val])=><div key={name}><span>{name}<b>{val}</b></span><i><em style={{width:`${val}%`}}/></i></div>)}</div>
 <div className="issue-layout"><div><h2>Priority findings</h2><div className="issue-list">{(result.issues||[]).map((x,i)=><article className={`severity-${x.severity}`} key={x.title}><span>{String(i+1).padStart(2,'0')}</span><div><p>{x.severity} priority</p><h3>{x.title}</h3><p>{x.detail}</p><b><Check/> Recommended fix</b><p>{x.fix}</p></div></article>)}</div></div><aside><p className="eyebrow">Estimated repair scope</p><h2>{result.estimate?.label}</h2><div className="estimate-price"><span>from</span><b>${result.estimate?.price?.toLocaleString()}</b></div><p>Estimated effort: {result.estimate?.effort}</p><p>This is a preliminary range based on the public crawl. We confirm scope before charging.</p><Link to={`/contact?audit=${encodeURIComponent(result.url)}&estimate=${result.estimate?.price}`} className="button button-acid">Request this repair <ArrowRight/></Link><a href={`mailto:hello.rarescore@gmail.com?subject=${encodeURIComponent(`SEO audit for ${result.url}`)}`} className="text-link">Email the studio</a></aside></div>
 <div className="result-disclaimer"><Info/><p>This audit covers one publicly accessible page and observable technical/on-page signals. It does not replace a full crawl, backlink review, analytics analysis, competitor research, manual accessibility audit or Search Console data.</p></div></div></section>}
