import { useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { ArrowRight, CheckCircle2, LoaderCircle, Mail } from 'lucide-react'
import Seo from '../components/Seo'
import { plans } from '../data'

const budgets=['Under $1,000','$1,000–$2,500','$2,500–$5,000','$5,000–$10,000','$10,000+','Not sure yet']
const needs=['Monthly marketing','AI video & social','Paid lead generation','SEO & local search','Performance website','Custom project']

export default function Contact(){
 const[params]=useSearchParams();const suggested=useMemo(()=>{const plan=plans.find(p=>p.id===params.get('plan'));return plan?`${plan.name} — $${plan.price.toLocaleString()}/month`:params.get('project')==='website'?'Performance website':params.get('project')==='custom'?'Custom project':''},[params])
 const[status,setStatus]=useState('idle');const[message,setMessage]=useState('');const[form,setForm]=useState({name:'',email:'',phone:'',company:'',website:params.get('audit')||'',need:suggested||'',budget:'',details:params.get('audit')?`I ran the audit for ${params.get('audit')}. Preliminary repair estimate: $${params.get('estimate')||''}.`:''})
 const update=e=>setForm({...form,[e.target.name]:e.target.value})
 async function submit(e){e.preventDefault();setStatus('loading');setMessage('');try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,source:location.href})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Message could not be sent.');if(d.needsSetup){setStatus('fallback');return}setStatus('success')}catch(err){setMessage(err.message);setStatus('fallback')}}
 if(status==='success')return <><Seo title="Thank you | LG Growth Studio" noindex/><section className="contact-success"><div><CheckCircle2/><p className="eyebrow">Request received</p><h1>We have the brief.</h1><p>Expect a response at <b>{form.email}</b> within one business day. We will review the fit before recommending a scope.</p><a className="button button-dark" href="/">Return home <ArrowRight/></a></div></section></>
 return <><Seo title="Contact LG Growth Studio | Start a Growth Project" description="Tell LG Growth Studio what you are trying to grow. Request monthly marketing, AI video, paid ads, SEO, a performance website or custom work."/>
 <section className="contact-page"><div className="wrap contact-grid"><div className="contact-copy"><p className="eyebrow">Start a project</p><h1>Tell us what needs<br/>to <i>move.</i></h1><p>Share the goal, the constraint and what you have already tried. We will recommend the smallest serious scope—not automatically the most expensive one.</p><div className="contact-direct"><span><Mail/> Direct email</span><a href="mailto:hello.rarescore@gmail.com">hello.rarescore@gmail.com</a><p>Typical response: within one business day</p></div><div className="what-next"><b>What happens next</b><span><i>1</i> We read the context</span><span><i>2</i> We assess fit and scope</span><span><i>3</i> You get a clear recommendation</span></div></div>
 <form className="project-form" onSubmit={submit}><div className="form-head"><span>PROJECT INQUIRY</span><b>01 / 01</b></div><div className="two-fields"><label>Your name<input name="name" value={form.name} onChange={update} autoComplete="name" required/></label><label>Work email<input type="email" name="email" value={form.email} onChange={update} autoComplete="email" required/></label></div><div className="two-fields"><label>Phone <span>(optional)</span><input name="phone" value={form.phone} onChange={update} autoComplete="tel"/></label><label>Company<input name="company" value={form.company} onChange={update} autoComplete="organization" required/></label></div><label>Current website <span>(optional)</span><input name="website" value={form.website} onChange={update} inputMode="url" placeholder="https://"/></label><fieldset><legend>What do you need?</legend><div className="choice-grid">{needs.map(n=><label key={n}><input type="radio" name="need" value={n} checked={form.need===n} onChange={update}/><span>{n}</span></label>)}</div></fieldset><label>Monthly working budget<select name="budget" value={form.budget} onChange={update} required><option value="">Choose a range</option>{budgets.map(b=><option key={b}>{b}</option>)}</select></label><label>What are you trying to accomplish?<textarea name="details" value={form.details} onChange={update} rows="6" placeholder="The goal, the current bottleneck, timeline, and anything we should know…" required/></label>{status==='fallback'&&<div className="form-fallback"><p>{message||'The direct email connection is not configured on this deployment yet.'}</p><a href={`mailto:hello.rarescore@gmail.com?subject=${encodeURIComponent(`Project inquiry from ${form.name}`)}&body=${encodeURIComponent(`Name: ${form.name}\nCompany: ${form.company}\nNeed: ${form.need}\nBudget: ${form.budget}\nWebsite: ${form.website}\n\n${form.details}`)}`}>Send the same brief by email</a></div>}<button className="button button-acid" disabled={status==='loading'}>{status==='loading'?<><LoaderCircle className="spin"/> Sending…</>:<>Send project brief <ArrowRight/></>}</button><small>By submitting, you agree that we may use this information to respond to your inquiry. No mailing-list enrollment.</small></form></div></section></>
}
