import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowRight, ArrowUpRight, Check, Minus } from 'lucide-react'
import Seo from '../components/Seo'
import { FaqList, SectionIntro } from '../components/UI'
import { faqs, plans } from '../data'

const comparison=[
  ['Managed channels','2','3','Up to 4','Up to 5'],['Monthly short videos','2','6','16','Up to 30'],['Total social assets','8','12','20','Daily cadence'],['Publishing','—','Included','Included','Included'],['Paid media management','—','Add-on','1 channel','4 platforms'],['Google Business Profile','Tune-up','Tune-up','Managed','Managed'],['SEO authority content','—','—','Add-on','2 / month'],['Strategy cadence','Report','Monthly','Monthly + weekly optimization','Weekly meeting'],
]

export default function Pricing(){
 const [loading,setLoading]=useState(''); const navigate=useNavigate()
 const begin=async(id)=>{setLoading(id);try{const res=await fetch('/api/create-checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan:id})});const data=await res.json();if(data.url){window.location.assign(data.url);return}}catch(error){console.info('Checkout is not configured; opening project inquiry.',error)}navigate(`/contact?plan=${id}`)}
 return <><Seo title="Marketing Packages & Pricing | RS Marketing" description="Compare RS Marketing monthly plans from $500 to $5,000, plus search-ready performance websites beginning at $1,500."/>
 <section className="page-hero pricing-hero"><div className="wrap"><p className="eyebrow">Simple scopes · serious work</p><h1>Choose the operating level.<br/><i>Keep the visibility.</i></h1><p className="page-lede">Monthly management pays for the team and system. Advertising spend stays separate, inside accounts you own.</p></div></section>
 <section className="plans-section"><div className="wrap plans-grid">{plans.map(p=><article id={p.id} className={`plan-card ${p.popular?'popular':''}`} key={p.id}>{p.popular&&<span className="popular-tag">Most selected</span>}<div className="plan-top"><p>{p.eyebrow}</p><h2>{p.name}</h2><p>{p.description}</p><div className="plan-price"><strong>${p.price.toLocaleString()}</strong><span>per month</span></div><button onClick={()=>begin(p.id)} disabled={loading===p.id} className={`button ${p.popular?'button-acid':'button-dark'}`}>{loading===p.id?'Opening…':'Start this plan'} <ArrowUpRight/></button></div><div className="plan-scope"><b>Best for</b><p>{p.bestFor}</p><b>Included</b><ul>{p.features.map(x=><li key={x}><Check/>{x}</li>)}</ul><div className="plan-exclusion"><Minus/>{p.notIncluded}</div></div></article>)}</div><div className="wrap pricing-disclosure"><p>Plans are month-to-month; a three-month runway is recommended to create, measure and improve. Final scope, billing date, approvals and cancellation terms are confirmed in your service agreement.</p></div></section>
 <section className="website-offer section" id="website"><div className="wrap website-offer-card"><div><p className="eyebrow">One-time build</p><h2>Performance website<br/><i>from $1,500.</i></h2><p>A focused, premium foundation for a local or professional-service business. Designed mobile-first, built for search clarity and connected to a working lead path.</p><Link className="button button-acid" to="/contact?project=website">Scope my website <ArrowUpRight/></Link></div><div><span className="site-score"><b>90+</b><small>launch target*</small></span><ul>{['Strategy and offer architecture','Up to 5 core pages','Original responsive visual system','Technical and on-page SEO','Schema, sitemap and metadata','Analytics and Search Console setup','Contact flow and launch QA'].map(x=><li key={x}><Check/>{x}</li>)}</ul><p className="fine-print">*Performance and SEO targets are verified on the final deployment. Exact Lighthouse scores depend on hosting, integrations, content and third-party scripts; no score is guaranteed before testing.</p></div></div></section>
 <section className="comparison-section section"><div className="wrap"><SectionIntro eyebrow="Compare the system" title={'The details,<br/><i>side by side.</i>'}/><div className="comparison-table" role="region" aria-label="Plan comparison" tabIndex="0"><table><thead><tr><th>Capability</th>{plans.map(p=><th key={p.id}>{p.name}<small>${p.price.toLocaleString()}/mo</small></th>)}</tr></thead><tbody>{comparison.map(row=><tr key={row[0]}>{row.map((x,i)=><td key={x}>{i===0?<b>{x}</b>:x}</td>)}</tr>)}</tbody></table></div></div></section>
 <section className="faq-section section"><div className="wrap faq-grid"><SectionIntro eyebrow="Before you subscribe" title={'The scope should feel<br/><i>clear before the call.</i>'}/><FaqList items={faqs}/></div></section>
 <section className="pricing-final"><div className="wrap"><h2>Not sure which level fits?</h2><p>Tell us the goal, budget and current bottleneck. We will recommend the smallest scope that can realistically do the job.</p><Link to="/contact" className="button button-acid">Get a straight recommendation <ArrowRight/></Link></div></section>
 </>}
