import { Link } from 'react-router-dom'
import { ArrowRight, ArrowUpRight, Check } from 'lucide-react'
import Seo from '../components/Seo'
import { Marquee, SectionIntro } from '../components/UI'
import { processSteps, services } from '../data'

const groups=[
  {id:'creative',n:'01',title:'Creative that earns the second look',copy:'We build repeatable concepts, not isolated content. Each series has a strategic job, a production logic and a testing plan.',items:['Creative direction and campaign concepts','AI-generated video scenes and variation','Scripts, hooks, captions and editing','Organic content calendars and publishing','Platform-native versions for short-form channels']},
  {id:'paid',n:'02',title:'Distribution that produces evidence',copy:'Media buying becomes more valuable when it is connected to the creative system and the sales process behind the form.',items:['Meta and Instagram campaign management','TikTok campaign management','Google Search and Performance Max consultation','Audience, offer and landing-page tests','Call, form and qualified-lead measurement']},
  {id:'search',n:'03',title:'Search assets that compound',copy:'We organize your expertise into pages and signals that make the business easier to discover, understand and trust.',items:['Technical and on-page SEO','Search-intent and content architecture','Authority articles and internal linking','Google Business Profile management','Local landing pages and review workflows']},
  {id:'web',n:'04',title:'Websites built as decision systems',copy:'A premium site makes a complicated decision feel clear. We combine design, speed, accessibility, search structure and conversion operations.',items:['Strategy, UX writing and original visual direction','Responsive design and development','Schema, metadata, analytics and Search Console setup','Forms, lead routing and conversion events','Launch QA and owner handoff']},
]

export default function Services(){return <><Seo title="Digital Marketing Services | RS Marketing" description="Explore AI video, social media, paid advertising, SEO, local search, performance websites and lead operations from RS Marketing."/>
  <section className="page-hero dark-page"><div className="wrap"><p className="eyebrow">Capabilities</p><h1>One studio from first<br/>impression to <i>qualified action.</i></h1><p className="page-lede">The strongest growth systems share intelligence. Search questions shape videos. Ad response improves the offer. Sales feedback changes the landing page.</p></div></section><Marquee/>
  <section className="capability-index section"><div className="wrap"><SectionIntro eyebrow="What we can own" title={'Specialists where it matters.<br/><i>One accountable system.</i>'}/><div className="capability-cards">{services.map((s,i)=>{const Icon=s.icon;return <article key={s.title}><span>{String(i+1).padStart(2,'0')}</span><Icon/><h2>{s.title}</h2><p>{s.text}</p><ul>{s.deliverables.map(x=><li key={x}>{x}</li>)}</ul></article>})}</div></div></section>
  <section className="service-groups section"><div className="wrap">{groups.map(g=><article id={g.id} key={g.id}><div><span>{g.n}</span><h2>{g.title}</h2><p>{g.copy}</p><Link to="/contact" className="text-link">Discuss this service <ArrowUpRight/></Link></div><ul>{g.items.map(x=><li key={x}><Check/>{x}</li>)}</ul></article>)}</div></section>
  <section className="process-compact section"><div className="wrap"><SectionIntro eyebrow="A visible operating rhythm" title={'You always know<br/><i>what happens next.</i>'}/><div>{processSteps.map(p=><article key={p.number}><span>{p.number}</span><h3>{p.title}</h3><p>{p.text}</p></article>)}</div><Link to="/pricing" className="button button-dark">Compare monthly scopes <ArrowRight/></Link></div></section>
  <section className="custom-banner"><div className="wrap"><div><p className="eyebrow">Something else?</p><h2>Bring us the strange,<br/>specific problem.</h2></div><p>Campaign launches, sales collateral, unusual video concepts, platform migrations and focused repair work can be quoted as custom projects.</p><Link to="/contact?project=custom" className="button button-acid">Request custom work <ArrowUpRight/></Link></div></section>
  </>}
