import Link from "next/link";
import { InjuryHero } from "@/features/demos/injury-law/home-hero.client";
import { ConsultationForm } from "@/features/demos/injury-law/consultation-form.client";
import { homeFaqs, lawPhoneDisplay, lawPhoneHref, practiceAreas, processStages, resources } from "@/features/demos/injury-law/data";

export default function Page(){return <main id="injury-main">
  <InjuryHero/>
  <section className="il-call-strip"><div><strong>Talk through what happened.</strong><span>A direct call can be the fastest next step.</span></div><a href={lawPhoneHref}>Call {lawPhoneDisplay}</a></section>
  <section className="il-section il-why"><div className="il-shell"><div className="il-section__head"><div><p className="il-eyebrow">Why Lev &amp; On</p><h2>Prepared from the first call.</h2></div><p>We begin by protecting the record, identifying urgent questions, and giving you a direct explanation of what comes next.</p></div><div className="il-value-grid">{[["01","Early action","We identify evidence that can disappear and records worth preserving."],["02","Serious preparation","Every review is organized around responsibility, injuries, coverage, and timing."],["03","Direct answers","You hear what the next step is, what is still unknown, and who is responsible for it."]].map(([n,h,p])=><article key={h}><span aria-hidden="true">{n}</span><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
  <section className="il-section il-section--ink"><div className="il-shell"><div className="il-section__head"><div><p className="il-eyebrow">Practice areas</p><h2>Focused injury counsel.</h2></div><p>Each matter starts with its own evidence, insurance, medical, and timing questions.</p></div><div className="il-practice-grid">{practiceAreas.map((area,i)=><Link href={`/practice-areas/${area.slug}`} key={area.slug}><small>{String(i+1).padStart(2,"0")}</small><h3>{area.name}</h3><p>{area.short}</p><span>Explore this area →</span></Link>)}</div></div></section>
  <section className="il-section"><div className="il-shell"><div className="il-section__head"><div><p className="il-eyebrow">Our process</p><h2>Five clear steps.</h2></div><p>No manufactured urgency. No unexplained handoffs.</p></div><ol className="il-process">{processStages.map(([h,p],i)=><li key={h}><b>{String(i+1).padStart(2,"0")}</b><div><h3>{h}</h3><p>{p}</p></div></li>)}</ol></div></section>
  <section className="il-checklist"><div className="il-shell il-content-grid"><div><p className="il-eyebrow">The first hours matter</p><h2>Protect your health. Then protect the record.</h2><Link className="il-button il-button--paper" href="/after-an-accident">Open the complete checklist</Link></div><ul>{["Get appropriate medical help","Photograph the scene and damage","Save witness and camera information","Keep reports and insurance messages","Avoid guessing about fault or injuries"].map(x=><li key={x}>{x}</li>)}</ul></div></section>
  <section className="il-section"><div className="il-shell"><div className="il-section__head"><div><p className="il-eyebrow">Featured resources</p><h2>Useful before the call.</h2></div><Link href="/resources">View all resources →</Link></div><div className="il-resource-grid">{resources.slice(0,3).map(r=><article className="il-resource-card" key={r.slug}><small>{r.category} · {r.readTime}</small><h3>{r.title}</h3><p>{r.summary}</p><Link href={`/resources/${r.slug}`}>Read the guide →</Link></article>)}</div></div></section>
  <section className="il-section il-faq"><div className="il-shell"><div className="il-section__head"><div><p className="il-eyebrow">Questions people ask</p><h2>Clear before complicated.</h2></div></div>{homeFaqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
  <section className="il-final-contact"><div className="il-shell il-content-grid"><div><p className="il-eyebrow">Free case review</p><h2>Tell us how to reach you.</h2><p>Our intake team will review your request and return your call. For immediate help, call <a href={lawPhoneHref}>{lawPhoneDisplay}</a>.</p></div><ConsultationForm source="homepage-footer"/></div></section>
</main>}
