export type ToolResult = { title: string; summary: string; metrics: { label: string; value: string }[]; flags: string[]; actions: string[]; assumptions: string[] };

export function triage(input: { symptom: string; active: boolean; hazard: string; multiple: boolean }): ToolResult {
  const emergency = input.hazard !== "none" || (input.active && ["leak", "sewer"].includes(input.symptom));
  const category = input.symptom === "hot" ? "Water heating" : input.symptom === "drain" || input.symptom === "sewer" ? "Drain / sewer" : input.symptom === "pressure" ? "Pressure / flow" : "Leak / supply";
  return { title: emergency ? "Immediate safety path" : input.multiple ? "Prompt professional review" : "Document and request review", summary: emergency ? "A red-flag answer overrides ordinary triage. Use the safety guidance now; do not wait for this website." : `Your answers organize this as a ${category.toLowerCase()} request. This is a service category, not a diagnosis.`, metrics: [{ label: "Service category", value: category }, { label: "Suggested timing", value: emergency ? "Immediate human escalation" : input.multiple ? "Prompt review" : "Scheduled review" }], flags: emergency ? ["Keep people away from the affected area.", "For gas odor, fire, electrical danger, or immediate danger, leave and contact 911/utility as appropriate.", "Use a known water shutoff only when safely accessible."] : ["Avoid equipment-specific adjustments based on an online result.", "Record when, where, and whether the condition changes."], actions: emergency ? ["Open immediate safety guidance", "Use the demo call path from a safe location"] : ["Photograph visible conditions without entering an unsafe area", "Prepare a qualified service request"], assumptions: ["Answers are homeowner observations only.", "No onsite inspection, measurement, code profile, or manufacturer data was reviewed."] };
}

export function waterHeater(input: { people: number; showers: number; minutes: number; gpm: number; rise: number; tank: number; input: number; efficiency: number }): ToolResult {
  const showerDemand = input.showers * input.minutes * input.gpm * 0.7;
  const fixtureAllowance = input.people * 2.5;
  const peak = showerDemand + fixtureAllowance;
  const recovery = input.input * 1000 * input.efficiency / (8.33 * input.rise);
  const firstHour = input.tank * 0.7 + recovery;
  const band = firstHour >= peak * 1.15 ? "Indicative buffer" : firstHour >= peak ? "Close preliminary fit" : "Demand exceeds this simplified band";
  return { title: "Demand + recovery worksheet", summary: "This compares a simplified peak-use scenario with an indicative first-hour supply. It does not select or approve equipment.", metrics: [{ label: "Estimated peak hot-water use", value: `${Math.round(peak)} gal` }, { label: "Indicative recovery", value: `${Math.round(recovery)} gal/hr` }, { label: "Simplified first-hour supply", value: `${Math.round(firstHour)} gal` }, { label: "Preliminary band", value: band }], flags: band.includes("exceeds") ? ["Review demand timing, temperature rise, equipment condition, and replacement options onsite."] : ["A numerical buffer does not verify venting, fuel, electrical, drainage, installation, or condition."], actions: ["Bring model, serial, fuel type, location, and age to a licensed review", "Confirm manufacturer-rated first-hour or recovery data"], assumptions: ["70% shower hot-water fraction", `${input.rise}°F temperature rise`, `${Math.round(input.efficiency * 100)}% user-entered thermal efficiency`, "No standby loss or mixed fixture concurrency model"] };
}

const flowGuide: Record<string, number> = { "1/2": 4, "3/4": 8, "1": 13, "1-1/4": 20 };
export function branchGuide(input: { size: string; fixtures: number; showers: number; appliances: number; pressure: number }): ToolResult {
  const demand = input.fixtures * 0.55 + input.showers * 1.8 + input.appliances * 1.25;
  const base = flowGuide[input.size] ?? 4;
  const adjusted = base * Math.min(1.1, Math.max(0.7, input.pressure / 60));
  return { title: "Preliminary branch worksheet", summary: demand <= adjusted ? "The simplified demand sits inside the selected educational guide band." : "The simplified demand exceeds the selected educational guide band and deserves licensed review.", metrics: [{ label: "Simplified demand", value: `${demand.toFixed(1)} guide GPM` }, { label: "Indicative branch band", value: `${adjusted.toFixed(1)} guide GPM` }, { label: "Selected branch", value: `${input.size} in nominal` }], flags: ["This is not a fixture-unit calculation, pipe-sizing design, or code-compliance result.", "Length, material, fittings, elevation, temperature, velocity, local code, and simultaneous use can change a real design."], actions: ["Create an actual fixture inventory", "Review material, developed length, available pressure, and applicable code with a licensed plumber"], assumptions: ["Illustrative guide profile FS-2026-DEMO", "User-entered pressure used only as a bounded adjustment", "No jurisdiction profile applied"] };
}

export function pressureFlow(input: { staticPsi: number; residualPsi: number; gpm: number; elevation: number; target: number }): ToolResult {
  const drop = input.staticPsi - input.residualPsi;
  const percent = input.staticPsi ? drop / input.staticPsi * 100 : 0;
  const elevationAdjustment = input.elevation * 0.433;
  const adjusted = input.residualPsi - elevationAdjustment;
  return { title: "Field measurement record", summary: "The worksheet records a test condition and pressure change. One test cannot determine the cause.", metrics: [{ label: "Observed static pressure", value: `${input.staticPsi.toFixed(1)} PSI` }, { label: "Observed residual pressure", value: `${input.residualPsi.toFixed(1)} PSI at ${input.gpm.toFixed(1)} GPM` }, { label: "Observed pressure drop", value: `${drop.toFixed(1)} PSI · ${percent.toFixed(0)}%` }, { label: "Elevation-adjusted residual", value: `${adjusted.toFixed(1)} PSI` }, { label: "Compared with target flow", value: input.gpm >= input.target ? "Observed test met target" : "Observed test below target" }], flags: [input.residualPsi > input.staticPsi ? "Residual pressure is above static pressure; repeat the test and verify entries." : "Do not infer a regulator, leak, restriction, or pipe condition from one reading."], actions: ["Record gauge location, date, test outlet, and active fixtures", "Repeat under comparable conditions and discuss with a licensed plumber"], assumptions: ["0.433 PSI per foot elevation adjustment", "Gauge accuracy and test method not verified", "No utility, regulator, or pipe inspection"] };
}

export function repipeScope(input: { stories: number; baths: number; fixtures: number; access: string; occupied: boolean; material: string }): ToolResult {
  const zones = Math.max(3, input.stories + input.baths + Math.ceil(input.fixtures / 6));
  const score = input.stories + input.baths + (input.access === "limited" ? 3 : input.access === "mixed" ? 2 : 1) + (input.occupied ? 2 : 0) + (input.material === "unknown" ? 1 : 0);
  const complexity = score >= 9 ? "High coordination" : score >= 6 ? "Moderate coordination" : "Lower coordination";
  return { title: "Preliminary repipe discussion scope", summary: "This organizes zones, access, occupancy, and finish questions. It is not a price, material prescription, or construction scope.", metrics: [{ label: "Planning zones", value: `${zones} preliminary zones` }, { label: "Coordination band", value: complexity }, { label: "Known supply material", value: input.material }], flags: ["Concealed routing, hazardous materials, structural conditions, fire assemblies, permits, and finish restoration require onsite review.", "Do not open walls based on this result."], actions: ["Map fixture groups and known shutoffs by floor", "Discuss temporary water, occupancy, protection, patching, inspections, and finish responsibility", "Request written inclusions, exclusions, and change-order conditions"], assumptions: ["Zones are an organizational aid only", "No destructive inspection or jurisdiction profile", `${input.fixtures} user-counted fixtures`] };
}

export function sewerEvidence(input: { locations: number; recurring: boolean; camera: boolean; cleanout: string; material: string }): ToolResult {
  const readiness = (input.locations > 0 ? 1 : 0) + (input.recurring ? 1 : 0) + (input.camera ? 2 : 0) + (input.cleanout !== "unknown" ? 1 : 0) + (input.material !== "unknown" ? 1 : 0);
  return { title: "Drain / sewer evidence brief", summary: readiness >= 5 ? "You have a stronger evidence set for an inspection conversation." : "Several useful evidence gaps remain before a repair-scope conversation.", metrics: [{ label: "Affected locations", value: String(input.locations) }, { label: "Pattern", value: input.recurring ? "Recurring" : "First observed" }, { label: "Camera evidence", value: input.camera ? "Reported available" : "Not available" }, { label: "Evidence readiness", value: `${readiness}/6` }], flags: ["This cannot locate a blockage, identify pipe failure, or prescribe cleaning or repair.", "Stop using affected fixtures and avoid exposure when sewage is present."], actions: [input.camera ? "Bring the full video, stills, date, access point, and written observations" : "Ask whether camera inspection is appropriate after safe access is established", "Document affected fixtures, timing, recurrence, prior work, and cleanout access"], assumptions: ["Evidence is owner-reported and unverified", `Cleanout: ${input.cleanout}`, `Known material: ${input.material}`] };
}
