import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { articles } from '../src/articles.js';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const pub=path.join(root,'public');
const base=(process.env.VITE_SITE_URL||process.env.SITE_URL||'https://lggrowthstudio.com').replace(/\/$/,'');
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const staticPages=['/','/audit','/process','/reviews','/pricing','/build-website','/contact','/articles'];
const urls=staticPages.map(p=>`<url><loc>${base}${p}</loc><lastmod>2026-08-08</lastmod><changefreq>${p==='/'||p==='/articles'?'weekly':'monthly'}</changefreq><priority>${p==='/'?'1.0':p==='/articles'?'.9':'.8'}</priority></url>`);
for(const a of articles)urls.push(`<url><loc>${base}/articles/${a.slug}</loc><lastmod>${a.datePublished}</lastmod><changefreq>monthly</changefreq><priority>.8</priority><image:image><image:loc>${base}${a.image}</image:loc><image:title>${esc(a.title)}</image:title></image:image></url>`);
fs.writeFileSync(path.join(pub,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n${urls.join('\n')}\n</urlset>\n`);
fs.writeFileSync(path.join(pub,'robots.txt'),`User-agent: *\nAllow: /\nDisallow: /api/\n\nSitemap: ${base}/sitemap.xml\n`);
const feedItems=articles.map(a=>`<item><title><![CDATA[${a.title}]]></title><link>${base}/articles/${a.slug}</link><guid>${base}/articles/${a.slug}</guid><pubDate>Sat, 08 Aug 2026 20:00:00 GMT</pubDate><description><![CDATA[${a.meta}]]></description></item>`).join('\n');
fs.writeFileSync(path.join(pub,'feed.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0"><channel><title>LG Growth Studio Research</title><link>${base}/articles</link><description>Research on websites, SEO, performance and growth.</description><language>en-us</language>${feedItems}</channel></rss>`);

const nav=`<header><a href="/"><img src="/lg-growth-studio-logo.png" alt="LG Growth Studio"></a><nav><a href="/contact">Contact</a><a href="/audit">Audit</a><a href="/process">Process</a><a href="/reviews">Reviews</a><a href="/pricing">Pricing</a><a href="/articles">Articles</a></nav><a class="start" href="/build-website">Start</a><div class="dock"><a href="/audit"><b>◎</b>Audit</a><a class="active" href="/articles"><b>▤</b>Read</a><a href="/pricing"><b>$</b>Pricing</a><a href="/build-website"><b>＋</b>Start</a></div></header>`;
const footer=`<footer><img src="/lg-growth-studio-logo.png" alt="LG Growth Studio"><div><a href="/contact">Contact</a><a href="/audit">Audit</a><a href="/process">Process</a><a href="/pricing">Pricing</a><a href="/articles">Articles</a></div></footer>`;
const articleDir=path.join(pub,'articles');fs.mkdirSync(articleDir,{recursive:true});
const cards=articles.map((a,i)=>`<a class="hub-card" href="/articles/${a.slug}"><picture><source media="(max-width:700px)" srcset="${a.image.replace('.webp','-800.webp')}"><img src="${a.image}" alt="${esc(a.imageAlt)}" ${i>1?'loading="lazy"':''}></picture><div><small>${esc(a.category)} · ${esc(a.readingTime)}</small><h2>${esc(a.title)}</h2><p>${esc(a.dek)}</p><b>Read research →</b></div></a>`).join('');
fs.writeFileSync(path.join(articleDir,'index.html'),`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Research Articles on Web Design, SEO & Growth | LG Growth Studio</title><meta name="description" content="Long-form research from LG Growth Studio on website design, technical SEO, Core Web Vitals, AI search, accessibility, local SEO, security and growth."><link rel="canonical" href="${base}/articles"><meta property="og:title" content="LG Growth Studio Research"><meta property="og:description" content="Research on websites, SEO, performance, AI search, accessibility, security and growth."><meta property="og:type" content="website"><meta property="og:image" content="${base}${articles[0].image}"><link rel="stylesheet" href="/article-static.css"><link rel="icon" href="/favicon.svg"></head><body>${nav}<main><section class="hub-hero"><span>LG Research Library</span><h1>Less noise.<br><em>More useful answers.</em></h1><p>Original long-form research on websites, search, performance, accessibility, security and growth—written for people who need to make decisions, not impress an algorithm.</p></section><section class="hub-grid">${cards}</section></main>${footer}</body></html>`);
for(const article of articles){
 const related=articles.filter(a=>a.slug!==article.slug).slice(0,3);
 const schema={"@context":"https://schema.org","@graph":[{"@type":"Article","headline":article.title,"description":article.meta,"image":`${base}${article.image}`,"datePublished":article.datePublished,"dateModified":article.datePublished,"author":{"@type":"Organization","name":"LG Growth Studio"},"publisher":{"@type":"Organization","name":"LG Growth Studio","url":base},"mainEntityOfPage":`${base}/articles/${article.slug}`,"keywords":[article.primaryKeyword,...article.keywords].join(', ')},{"@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":base},{"@type":"ListItem","position":2,"name":"Articles","item":`${base}/articles`},{"@type":"ListItem","position":3,"name":article.title,"item":`${base}/articles/${article.slug}`}]},{"@type":"FAQPage","mainEntity":article.faq.map(([q,a])=>({"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}}))}]};
 const toc=article.sections.map((s,i)=>`<a href="#section-${i+1}">${String(i+1).padStart(2,'0')} ${esc(s.heading)}</a>`).join('');
 const sections=article.sections.map((s,i)=>`<section id="section-${i+1}"><span class="num">${String(i+1).padStart(2,'0')}</span><h2>${esc(s.heading)}</h2>${s.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</section>`).join('');
 const faq=article.faq.map(([q,a])=>`<details><summary>${esc(q)}<span>+</span></summary><p>${esc(a)}</p></details>`).join('');
 const refs=article.sources.map(src=>`<li><a href="${esc(src.url)}" target="_blank" rel="noreferrer">${esc(src.label)} ↗</a></li>`).join('');
 const rel=related.map(a=>`<a href="/articles/${a.slug}"><span>${esc(a.category)}</span><h3>${esc(a.shortTitle)}</h3><b>Read →</b></a>`).join('');
 fs.writeFileSync(path.join(articleDir,`${article.slug}.html`),`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${esc(article.shortTitle)} | LG Growth Studio Research</title><meta name="description" content="${esc(article.meta)}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"><meta name="keywords" content="${esc([article.primaryKeyword,...article.keywords].join(', '))}"><link rel="canonical" href="${base}/articles/${article.slug}"><meta property="og:title" content="${esc(article.title)}"><meta property="og:description" content="${esc(article.meta)}"><meta property="og:type" content="article"><meta property="og:image" content="${base}${article.image}"><meta name="twitter:card" content="summary_large_image"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script><link rel="stylesheet" href="/article-static.css"><link rel="icon" href="/favicon.svg"></head><body>${nav}<main><article><header class="hero"><div class="hero-inner"><div class="hero-copy"><a class="hero-back" href="/articles">← Research library</a><div class="meta"><b>${esc(article.category)}</b><span>${esc(article.readingTime)}</span><time datetime="${article.datePublished}">Aug 8, 2026</time></div><h1>${esc(article.title)}</h1><p>${esc(article.dek)}</p></div><picture class="hero-media"><source media="(max-width:700px)" srcset="${article.image.replace('.webp','-800.webp')}"><img src="${article.image}" alt="${esc(article.imageAlt)}"></picture></div></header><div class="layout"><aside class="toc"><span>In this article</span>${toc}</aside><div class="content"><p class="lede">${esc(article.dek)}</p>${sections}<section class="faq"><span class="num">QUESTIONS</span><h2>Frequently asked</h2>${faq}</section><section class="sources"><span class="num">RESEARCH SOURCES</span><h2>References</h2><ol>${refs}</ol><p>Sources support factual claims and further reading. Analysis and recommendations are original to LG Growth Studio.</p></section><aside class="cta"><span>Apply the research</span><h2>See what this means for your website.</h2><p>Run the audit for a practical starting point, or send us the site if you want a human review of the highest-impact changes.</p><div><a class="button red" href="/audit">Run website audit</a><a class="button" href="/contact">Contact us</a></div></aside></div></div></article><section class="related"><span>Keep reading</span><h2>Related research</h2><div class="related-grid">${rel}</div></section></main>${footer}</body></html>`);
}
console.log(`SEO assets generated for ${base}`);
