export const metadata = { title: "Terms of Use" };
export default function Page() { return <main id="injury-main" className="il-legal"><p className="il-eyebrow">Terms</p><h1>Terms of Use</h1><p><strong>Effective August 25, 2026.</strong> By using this website, you agree to these terms. If you do not agree, do not use the site.</p>
  <h2>General information only</h2><p>The website provides general information about personal injury matters. It is not legal, medical, tax, or financial advice and cannot account for your facts, location, policies, or deadlines. Do not delay emergency care or professional advice because of something you read here.</p>
  <h2>No attorney-client relationship</h2><p>Visiting the site, calling the firm, or sending an inquiry does not make you a client. Representation begins only after the firm completes its review, confirms there is no disqualifying conflict, offers representation, and both the firm and client sign a written agreement. Until then, do not assume the firm is protecting a deadline or acting on your behalf.</p>
  <h2>Deadlines and emergencies</h2><p>This website does not calculate statutes of limitation, claim-notice periods, insurance deadlines, or court dates. They vary by jurisdiction and circumstance. Call 911 for an emergency and seek qualified medical care for serious or worsening symptoms.</p>
  <h2>Jurisdiction</h2><p>The site is intended to describe services concerning California personal injury matters. It is not an offer to provide legal services where doing so would violate local law or professional rules. A lawyer’s ability to assist depends on licensing, the facts, conflicts, deadlines, and a written engagement.</p>
  <h2>Attorney advertising and outcomes</h2><p>This website may be considered attorney advertising. Descriptions of practice areas are not claims of specialization or certification. No result is promised or guaranteed, and any future example, testimonial, award, or result must be understood in its full context.</p>
  <h2>Acceptable use</h2><p>Do not misuse the form, submit unlawful content, impersonate another person, attempt to bypass security, interfere with the site, or use automated tools to overload or scrape it. We may block abusive traffic and preserve related records.</p>
  <h2>Links and availability</h2><p>Links to government agencies and other third parties are provided for convenience. We do not control their content or privacy practices. We may update, suspend, or remove site content or features without notice. We do not warrant uninterrupted or error-free operation.</p>
  <h2>Intellectual property</h2><p>Unless otherwise stated, the site’s original text, design, graphics, and code are owned by or licensed to Lev &amp; On Law Firm. You may print or save a reasonable copy for personal, noncommercial use; other reproduction requires permission.</p>
  <h2>Applicable law and updates</h2><p>To the extent permitted by law, these terms are governed by California law, without regard to conflict-of-law rules. We may update the terms by posting a new effective date. Continued use after an update means you accept the revised terms.</p>
  </main>; }
