import Link from "next/link";
import { ViewTransition } from "react";
import { InjuryHero } from "@/features/demos/injury-law/home-hero.client";
import { InjuryCta } from "@/features/demos/injury-law/injury-layout";
import { attorneys, demoLawPhoneHref, injuryBase, practiceAreas, processStages, resources } from "@/features/demos/injury-law/data";

export default function InjuryLawDemoPage() {
  return <main id="injury-main">
    <ViewTransition name="portal-injury-law" share="portal-morph" default="none"><InjuryHero /></ViewTransition>
    <section className="il-safety" aria-label="Immediate medical and safety guidance"><div className="il-shell il-safety__inner"><strong>Safety before legal questions</strong><p>If anyone may be in immediate danger, call 911. A website cannot assess medical urgency; seek appropriate care for new, severe, or worsening symptoms.</p><Link href={`${injuryBase}/after-an-accident`}>Open the immediate guide</Link></div></section>
    <section className="il-section"><div className="il-shell"><div className="il-section__head"><div><p className="il-eyebrow">Four things that matter first</p><h2>Stabilize the moment before deciding what comes next.</h2></div><div><p>An accident creates several problems at once. This system separates them into a sequence that is easier to act on.</p></div></div><div className="il-orientation">{[["01","Care","Address safety and medical needs. Keep instructions, appointments, and changes together."],["02","Evidence","Preserve photographs, reports, witnesses, original messages, and physical items."],["03","Communication","Keep a record of insurer calls and requests. Do not guess when you do not know."],["04","Timing","Rights and deadlines depend on jurisdiction. Get qualified advice rather than relying on a generic calculator."]].map(([n,t,c])=><article key={n}><small>{n}</small><h3>{t}</h3><p>{c}</p></article>)}</div></div></section>
    <section className="il-review-preview il-section"><div className="il-shell il-review-preview__grid"><div><p className="il-eyebrow il-eyebrow--inverse">Incident &amp; Impact Review</p><h2>Useful guidance before a contact form.</h2><p>A quiet, six-stage review identifies immediate actions, evidence to preserve, documentation gaps, and when human review may be time-sensitive. It never produces a case score or settlement estimate.</p><Link className="il-button il-button--paper" href={`${injuryBase}/case-review`}>Start the review <span aria-hidden="true">→</span></Link></div><div className="il-output-sheet"><p className="il-eyebrow">Your orientation · Example output</p><h3 className="il-output-sheet__title">A clear next-step record</h3><div className="il-output-sheet__rule"/><ul><li><span>Immediate</span><strong>Care and safety guidance</strong></li><li><span>Preserve</span><strong>Evidence action list</strong></li><li><span>Complete</span><strong>Documentation gaps</strong></li><li><span>Discuss</span><strong>Human review timing</strong></li></ul></div></div></section>
    <section className="il-section"><div className="il-shell"><div className="il-section__head"><div><p className="il-eyebrow">Practice areas</p><h2>Different incidents. One disciplined way to find clarity.</h2></div><div><p>Each route begins with practical steps and records—not dramatic images or promises about outcomes.</p></div></div><div className="il-matter-list">{practiceAreas.map((area,index)=><Link key={area.slug} href={`${injuryBase}/practice-areas/${area.slug}`}><b>{String(index+1).padStart(2,"0")}</b><h3>{area.name}</h3><p>{area.short}</p><i aria-hidden="true">↗</i></Link>)}</div></div></section>
    <section className="il-section il-section--bright"><div className="il-shell"><div className="il-section__head"><div><p className="il-eyebrow">How the process works</p><h2>A record line, not a promise.</h2></div><div><p>Every matter follows a different path. The system makes the questions and possible stages understandable while a qualified lawyer supplies jurisdiction-specific advice.</p><Link href={`${injuryBase}/process`} className="il-inline-link">See the process in detail</Link></div></div><div className="il-process-line">{processStages.map(([title,copy],index)=><article key={title}><small>{String(index+1).padStart(2,"0")}</small><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="il-section"><div className="il-shell"><div className="il-section__head"><div><p className="il-eyebrow">People before positioning</p><h2>Calm counsel. Clear roles.</h2></div><div><p>These are explicitly fictional demonstration profiles. No credentials, awards, rankings, or case outcomes are invented.</p></div></div><div className="il-people">{attorneys.map((person)=><article className="il-person" data-initials={person.initials} key={person.slug}><h3>{person.name}</h3><p>{person.role}</p><p>{person.focus}</p><Link href={`${injuryBase}/attorneys/${person.slug}`}>Read demonstration profile</Link></article>)}</div></div></section>
    <section className="il-section il-section--quiet"><div className="il-shell"><div className="il-section__head"><div><p className="il-eyebrow">Resources, not pressure</p><h2>Understand the record you are building.</h2></div><div><p>Plain-language educational material for common questions. It is general information and not legal or medical advice.</p></div></div><div className="il-resource-grid">{resources.map((resource)=><article className="il-resource-card" key={resource.slug}><small>{resource.category} · {resource.readTime}</small><h3>{resource.title}</h3><p>{resource.summary}</p><Link href={`${injuryBase}/resources/${resource.slug}`}>Read guide</Link></article>)}</div></div></section>
    <InjuryCta title="You do not have to organize every detail alone." copy="Use the guided review first, or request a no-pressure conversation. If you need immediate safety or medical help, use emergency services or an appropriate healthcare professional." href={`${injuryBase}/consultation`} label="Request a conversation" />
    <div className="il-safety"><div className="il-shell il-safety__inner"><strong>Prefer to speak?</strong><p>The demonstration call path is always available and never depends on a quiz result.</p><a href={demoLawPhoneHref}>Call the demo human-help line</a></div></div>
  </main>;
}
